version: "3.4"
services:
  beacon:
    image: chainsafe/lodestar:next
    restart: always
    volumes:
      - ./beacon_data:/data
      - "../../../genesis-states/${TESTNET_NAME}/public:/testnet_config_data"
      - "../../../genesis-states/${TESTNET_NAME}/private/validator_0:/validator_keys"
    command: >
      dev --rootDir /data --genesisValidators 32 --startValidators 0:31
      --api.rest.enabled --api.rest.host 0.0.0.0
      --logFile /logs/beacon.log --logLevelFile debug --logRotate --logMaxFiles 5
      --params.ALTAIR_FORK_EPOCH 0
      --params.MERGE_FORK_EPOCH 0
      --params.TRANSITION_TOTAL_DIFFICULTY 0
      --execution.urls http://localhost:8550
    environment:
      NODE_OPTIONS: --max_old_space_size=6144
    network_mode: host
