version: "3.4"
services:
  beacon:
    image: chainsafe/lodestar:next
    restart: always
    volumes:
      - ./beacon_data:/data
      - "../../../genesis-states/${TESTNET_NAME}/public:/testnet_config_data"
      - "../../../genesis-states/${TESTNET_NAME}/private/validator_0:/validator_keys"
    command: >
          lodestar beacon --rcConfig amphora/v1/rcconfig.yml --rootDir /data
    environment:
      LODESTAR_PRESET=minimal
    network_mode: host
