version: "3.4"
services:
  geth:
    image: parithoshj/geth:merge-a0fe68b
    restart: always
    volumes:
      - ./geth_data:/data
    command: >
      --catalyst --http --ws -http.api "engine,eth,net" --datadir "/data"
    network_mode: host